export const CHANGE_AUTH_FORM_INPUT_VALUE = 'CHANGE_AUTH_FORM_INPUT_VALUE';
export const CHANGE_AUTH_FORM_VALIDATION_STATUS =
  'CHANGE_AUTH_FORM_VALIDATION_STATUS';
export const CHANGE_REGISTRATION_FORM_INPUT_VALUE =
  'CHANGE_REGISTRATION_FORM_INPUT_VALUE';
export const CHANGE_REGISTRATION_FORM_VALIDATION_STATUS =
  'CHANGE_REGISTRATION_FORM_VALIDATION_STATUS';

export const START_API_REQUEST = 'START_API_REQUEST';
export const FINISH_API_REQUEST = 'FINISH_API_REQUEST';
export const GET_REQUEST_ERROR = 'GET_REQUEST_ERROR';

export const SIGN_IN = 'USER/SIGN_IN';
export const LOGOUT = 'USER/LOGOUT';

export const SEND_REGISTRATION_REQUEST = 'SEND_REGISTRATION_REQUEST';
