export const CHANGE_AUTH_FORM_INPUT_VALUE = 'CHANGE_AUTH_FORM_INPUT_VALUE';
export const CHANGE_AUTH_FORM_VALIDATION_STATUS =
  'CHANGE_AUTH_FORM_VALIDATION_STATUS';
export const CHANGE_REGISTRATION_FORM_INPUT_VALUE =
  'CHANGE_REGISTRATION_FORM_INPUT_VALUE';
export const CHANGE_REGISTRATION_FORM_VALIDATION_STATUS =
  'CHANGE_REGISTRATION_FORM_VALIDATION_STATUS';
