export const CHANGE_AUTH_FORM_INPUT_VALUE = 'CHANGE_AUTH_FORM_INPUT_VALUE';
export const CHANGE_AUTH_FORM_VALIDATION_STATUS =
  'CHANGE_AUTH_FORM_VALIDATION_STATUS';
export const CHANGE_REGISTRATION_FORM_INPUT_VALUE =
  'CHANGE_REGISTRATION_FORM_INPUT_VALUE';
export const CHANGE_REGISTRATION_FORM_VALIDATION_STATUS =
  'CHANGE_REGISTRATION_FORM_VALIDATION_STATUS';

export const START_API_REQUEST = 'START_API_REQUEST';
export const FINISH_API_REQUEST = 'FINISH_API_REQUEST';
export const GET_REQUEST_ERROR = 'GET_REQUEST_ERROR';

export const SIGN_IN = 'SIGN_IN';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';

export const SEND_LOGOUT_REQUEST = 'SEND_LOGOUT_REQUEST';
export const SEND_GET_CURRENT_USER_REQUEST = 'SEND_GET_CURRENT_USER_REQUEST';
export const SEND_REGISTRATION_REQUEST = 'SEND_REGISTRATION_REQUEST';
export const SEND_AUTHORIZATION_REQUEST = 'SEND_AUTHORIZATION_REQUEST';

export const OPEN_MODAL_DIALOG = 'OPEN_MODAL_DIALOG';
export const CLOSE_MODAL_DIALOG = 'CLOSE_MODAL_DIALOG';

export const REQUEST_TESTS_FROM_SERVER = 'REQUEST_TESTS_FROM_SERVER';
export const GET_TESTS = 'GET_TESTS';
